"""
Music Training note mapping.

This module contains an array of dictionaries containing music note mappings.

"""

note_mapping = [
    {'nid': '148',
     'name': 'C',
     'key': 'c3',
     'prefix': '',
     'position_factor': 8,
     'keyboard': 'c',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '147',
     'name': 'B',
     'key': 'b2',
     'prefix': '',
     'position_factor': 7,
     'keyboard': 'b',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '146',
     'name': 'Bes',
     'key': 'b2b',
     'prefix': 'b',
     'position_factor': 7,
     'keyboard': 'b',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '146',
     'name': 'Ais',
     'key': 'a2#',
     'prefix': '#',
     'position_factor': 6,
     'keyboard': 'a',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '145',
     'name': 'A',
     'key': 'a2',
     'prefix': '',
     'position_factor': 6,
     'keyboard': 'a',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '144',
     'name': 'As',
     'key': 'a2b',
     'prefix': 'b',
     'position_factor': 6,
     'keyboard': 'a',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '144',
     'name': 'Gis',
     'key': 'g2#',
     'prefix': '#',
     'position_factor': 5,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '143',
     'name': 'G',
     'key': 'g2',
     'prefix': '',
     'position_factor': 5,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '142',
     'name': 'Ges',
     'key': 'g2b',
     'prefix': 'b',
     'position_factor': 5,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '142',
     'name': 'Fis',
     'key': 'f2#',
     'prefix': '#',
     'position_factor': 4,
     'keyboard': 'f',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '141',
     'name': 'F',
     'key': 'f2',
     'prefix': '',
     'position_factor': 4,
     'keyboard': 'f',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '140',
     'name': 'E',
     'key': 'e2',
     'prefix': '',
     'position_factor': 3,
     'keyboard': 'e',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '139',
     'name': 'Es',
     'key': 'e2b',
     'prefix': 'b',
     'position_factor': 3,
     'keyboard': 'e',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '139',
     'name': 'Dis',
     'key': 'd2#',
     'prefix': '#',
     'position_factor': 2,
     'keyboard': 'd',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '138',
     'name': 'D',
     'key': 'd2',
     'prefix': '',
     'position_factor': 2,
     'keyboard': 'd',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '137',
     'name':  'Des',
     'key': 'd2b',
     'prefix': 'b',
     'position_factor': 2,
     'keyboard': 'd',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '137',
     'name':  'Cis',
     'key': 'c2#',
     'prefix': '#',
     'position_factor': 1,
     'keyboard': 'c',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '136',
     'name':  'C',
     'key': 'c2',
     'prefix': '',
     'position_factor': 1,
     'keyboard': 'c',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '135',
     'name':  'B',
     'key': 'b1',
     'prefix': '',
     'position_factor': 0,
     'keyboard': 'b',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '134',
     'name':  'Bes',
     'key': 'b1b',
     'prefix': 'b',
     'position_factor': 0,
     'keyboard': 'b',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '134',
     'name':  'Ais',
     'key': 'a1#',
     'prefix': '#',
     'position_factor': -1,
     'keyboard': 'a',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '133',
     'name':  'A',
     'key': 'a1',
     'prefix': '',
     'position_factor': -1,
     'keyboard': 'a',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '132',
     'name':  'As',
     'key': 'a1b',
     'prefix': 'b',
     'position_factor': -1,
     'keyboard': 'a',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '132',
     'name':  'Gis',
     'key': 'g1#',
     'prefix': '#',
     'position_factor': -2,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '131',
     'name':  'G',
     'key': 'g1',
     'prefix': '',
     'position_factor': -2,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '130',
     'name':  'Ges',
     'key': 'g1b',
     'prefix': 'b',
     'position_factor': -2,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '130',
     'name':  'Fis',
     'key': 'f1#',
     'prefix':  '#',
     'position_factor': -3,
     'keyboard': 'f',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '129',
     'name':  'F',
     'key': 'f1',
     'prefix': '',
     'position_factor': -3,
     'keyboard': 'f',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '128',
     'name':  'E',
     'key': 'e1',
     'prefix': '',
     'position_factor': -4,
     'keyboard': 'e',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '127',
     'name':  'Es',
     'key': 'e1b',
     'prefix': 'b',
     'position_factor': -4,
     'keyboard': 'e',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '127',
     'name': 'Dis',
     'key': 'd1#',
     'prefix': '#',
     'position_factor': -5,
     'keyboard': 'd',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '126',
     'name': 'D',
     'key': 'd1',
     'prefix': '',
     'position_factor': -5,
     'keyboard': 'd',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '125',
     'name': 'Des',
     'key': 'd1b',
     'prefix': 'b',
     'position_factor': -5,
     'keyboard': 'b',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '125',
     'name': 'Cis',
     'key': 'c1#',
     'prefix': '#',
     'position_factor': -6,
     'keyboard': 'c',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '124',
     'name': 'C',
     'key': 'c1',
     'prefix': '',
     'position_factor': -6,
     'keyboard': 'c',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '123',
     'name': 'B',
     'key': 'b',
     'prefix': '',
     'position_factor': -7,
     'keyboard': 'b',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '122',
     'name': 'Bes',
     'key': 'bb',
     'prefix': 'b',
     'position_factor': -7,
     'keyboard': 'b',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '122',
     'name': 'Ais',
     'key': 'a#',
     'prefix': '#',
     'position_factor': -8,
     'keyboard': 'a',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '121',
     'name': 'A',
     'key': 'a',
     'prefix': '',
     'position_factor': -8,
     'keyboard': 'a',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '120',
     'name': 'As',
     'key': 'ab',
     'prefix': 'b',
     'position_factor': -8,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '120',
     'name': 'Gis',
     'key': 'g#',
     'prefix': '#',
     'position_factor': -9,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': False,
     },
    {'nid': '119',
     'name': 'G',
     'key': 'g',
     'prefix': '',
     'position_factor': -9,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': True,
     },
    {'nid': '130',
     'name': 'Ges',
     'key': 'g1b',
     'prefix': 'b',
     'position_factor': 10,
     'keyboard': 'f',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '130',
     'name': 'Fis',
     'key': 'f1#',
     'prefix': '#',
     'position_factor': 9,
     'keyboard': 'f',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '129',
     'name': 'F',
     'key': 'f1',
     'prefix': '',
     'position_factor': 9,
     'keyboard': 'f',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '128',
     'name': 'E',
     'key': 'e1',
     'prefix': '',
     'position_factor': 8,
     'keyboard': 'e',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '127',
     'name': 'Es',
     'key': 'e1b',
     'prefix': 'b',
     'position_factor': 8,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '127',
     'name': 'Dis',
     'key': 'd1#',
     'prefix': '#',
     'position_factor': 7,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '126',
     'name': 'D',
     'key': 'd1',
     'prefix': '',
     'position_factor': 7,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '125',
     'name': 'Des',
     'key': 'd1b',
     'prefix': 'b',
     'position_factor': 7,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '125',
     'name': 'Cis',
     'key': 'c1#',
     'prefix': '#',
     'position_factor': 6,
     'keyboard': 'c',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '124',
     'name': 'C',
     'key': 'c1',
     'prefix': '',
     'position_factor': 6,
     'keyboard': 'c',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '123',
     'name': 'B',
     'key': 'b',
     'prefix': '',
     'position_factor': 5,
     'keyboard': 'b',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '122',
     'name': 'Bes',
     'key': 'bb',
     'prefix': 'b',
     'position_factor': 5,
     'keyboard': 'b',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '122',
     'name': 'Ais',
     'key': 'a#',
     'prefix': '#',
     'position_factor': 4,
     'keyboard': 'a',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '121',
     'name': 'A',
     'key': 'a',
     'prefix': '',
     'position_factor': 4,
     'keyboard': 'a',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '120',
     'name': 'As',
     'key': 'ab',
     'prefix': 'b',
     'position_factor': 4,
     'keyboard': 'a',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '120',
     'name': 'Gis',
     'key': 'g#',
     'prefix': '#',
     'position_factor': 3,
     'keyboard': 'g',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '119',
     'name': 'G',
     'key': 'g',
     'prefix': '',
     'position_factor': 3,
     'keyboard': 'g',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '118',
     'name': 'Ges',
     'key': 'gb',
     'prefix': 'b',
     'position_factor': 3,
     'keyboard': 'f',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '118',
     'name': 'Fis',
     'key': 'f#',
     'prefix': '#',
     'position_factor': 2,
     'keyboard': 'f',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '117',
     'name': 'F',
     'key': 'f',
     'prefix': '',
     'position_factor': 2,
     'keyboard': 'f',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '116',
     'name': 'E',
     'key': 'e',
     'prefix': '',
     'position_factor': 1,
     'keyboard': 'e',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '115',
     'name': 'Es',
     'key': 'eb',
     'prefix': 'b',
     'position_factor': 1,
     'keyboard': 'e',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '115',
     'name': 'Dis',
     'key': 'd#',
     'prefix': '#',
     'position_factor': 0,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '114',
     'name': 'D',
     'key': 'd',
     'prefix': '',
     'position_factor': 0,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '113',
     'name': 'Des',
     'key': 'db',
     'prefix': 'b',
     'position_factor': 0,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '113',
     'name': 'Cis',
     'key': 'c#',
     'prefix': '#',
     'position_factor': -1,
     'keyboard': 'c',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '112',
     'name': 'C',
     'key': 'c',
     'prefix': '',
     'position_factor': -1,
     'keyboard': 'c',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '111',
     'name': 'B',
     'key': 'B',
     'prefix': '',
     'position_factor': -2,
     'keyboard': 'b',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '110',
     'name': 'Bes',
     'key': 'Bb',
     'prefix': 'b',
     'position_factor': -2,
     'keyboard': 'b',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '110',
     'name': 'Ais',
     'key': 'A#',
     'prefix': '#',
     'position_factor': -3,
     'keyboard': 'a',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '109',
     'name': 'A',
     'key': 'A',
     'prefix': '',
     'position_factor': -3,
     'keyboard': 'a',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '108',
     'name': 'As',
     'key': 'Ab',
     'prefix': 'b',
     'position_factor': -3,
     'keyboard': 'a',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '108',
     'name': 'Gis',
     'key': 'G#',
     'prefix': '#',
     'position_factor': -4,
     'keyboard': 'g',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '107',
     'name': 'G',
     'key': 'G',
     'prefix': '',
     'position_factor': -4,
     'keyboard': 'g',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '106',
     'name': 'Ges',
     'key': 'Gb',
     'prefix': 'b',
     'position_factor': -4,
     'keyboard': 'g',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '106',
     'name': 'Fis',
     'key': 'F#',
     'prefix': '#',
     'position_factor': -5,
     'keyboard': 'f',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '105',
     'name': 'F',
     'key': 'F',
     'prefix': '',
     'position_factor': -5,
     'keyboard': 'f',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '104',
     'name': 'E',
     'key': 'E',
     'prefix': '',
     'position_factor': -6,
     'keyboard': 'e',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '103',
     'name': 'Es',
     'key': 'Eb',
     'prefix': 'b',
     'position_factor': -6,
     'keyboard': 'e',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '103',
     'name': 'Dis',
     'key': 'D#',
     'prefix': '#',
     'position_factor': -7,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '102',
     'name': 'D',
     'key': 'D',
     'prefix': '',
     'position_factor': -7,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': True,
     },
    {'nid': '101',
     'name': 'Des',
     'key': 'Db',
     'prefix': 'b',
     'position_factor': -7,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '101',
     'name': 'Cis',
     'key': 'C#',
     'prefix': '#',
     'position_factor': -8,
     'keyboard': 'c',
     'clef': 'f',
     'white_key': False,
     },
    {'nid': '100',
     'name': 'C',
     'key': 'C',
     'prefix': '',
     'position_factor': -8,
     'keyboard': 'c',
     'clef': 'f',
     'white_key': True,
     },
]

