"""
Music Training key mapping.

This module contains an array of dictionaries containing music note mappings.

"""

note_mapping = [
    {'pid': '148',
     'key': 'c3',
     'position_factor': 8,
     'keyboard': 'c',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '147',
     'key': 'b2',
     'position_factor': 7,
     'keyboard': 'b',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '146',
     'key': 'b2b',
     'position_factor': 7,
     'keyboard': 'b',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '146',
     'key': 'a2#',
     'position_factor': 6,
     'keyboard': 'a',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '145',
     'key': 'a2',
     'position_factor': 6,
     'keyboard': 'a',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '144',
     'key': 'a2b',
     'position_factor': 6,
     'keyboard': 'a',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '144',
     'key': 'g2#',
     'position_factor': 5,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '143',
     'key': 'g2',
     'position_factor': 5,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '142',
     'key': 'g2b',
     'position_factor': 5,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '142',
     'key': 'f2#',
     'position_factor': 4,
     'keyboard': 'f',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '141',
     'key': 'f2',
     'position_factor': 4,
     'keyboard': 'f',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '140',
     'key': 'e2',
     'position_factor': 3,
     'keyboard': 'e',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '139',
     'key': 'e2b',
     'position_factor': 3,
     'keyboard': 'e',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '139',
     'key': 'd2#',
     'position_factor': 2,
     'keyboard': 'd',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '138',
     'key': 'd2',
     'position_factor': 2,
     'keyboard': 'd',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '137',
     'key': 'd2b',
     'position_factor': 2,
     'keyboard': 'd',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '137',
     'key': 'c2#',
     'position_factor': 1,
     'keyboard': 'c',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '136',
     'key': 'c2',
     'position_factor': 1,
     'keyboard': 'c',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '135',
     'key': 'b1',
     'position_factor': 0,
     'keyboard': 'b',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '134',
     'key': 'b1b',
     'position_factor': 0,
     'keyboard': 'b',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '134',
     'key': 'a1#',
     'position_factor': -1,
     'keyboard': 'a',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '133',
     'key': 'a1',
     'position_factor': -1,
     'keyboard': 'a',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '132',
     'key': 'a1b',
     'position_factor': -1,
     'keyboard': 'a',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '132',
     'key': 'g1#',
     'position_factor': -2,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '131',
     'key': 'g1',
     'position_factor': -2,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '130',
     'key': 'g1b',
     'position_factor': -2,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '130',
     'key': 'f1#',
     'position_factor': -3,
     'keyboard': 'f',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '129',
     'key': 'f1',
     'position_factor': -3,
     'keyboard': 'f',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '128',
     'key': 'e1',
     'position_factor': -4,
     'keyboard': 'e',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '127',
     'key': 'e1b',
     'position_factor': -6,
     'keyboard': 'e',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '127',
     'key': 'd1#',
     'position_factor': -5,
     'keyboard': 'd',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '126',
     'key': 'd1',
     'position_factor': -5,
     'keyboard': 'd',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '125',
     'key': 'd1b',
     'position_factor': -7,
     'keyboard': 'b',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '125',
     'key': 'c1#',
     'position_factor': -6,
     'keyboard': 'c',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '124',
     'key': 'c1',
     'position_factor': -6,
     'keyboard': 'c',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '123',
     'key': 'b',
     'position_factor': -7,
     'keyboard': 'b',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '123',
     'key': 'bb',
     'position_factor': -7,
     'keyboard': 'b',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '122',
     'key': 'a#',
     'position_factor': -8,
     'keyboard': 'a',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '121',
     'key': 'a',
     'position_factor': -8,
     'keyboard': 'a',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '120',
     'key': 'ab',
     'position_factor': -8,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '120',
     'key': 'g#',
     'position_factor': -9,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': False,
     },
    {'pid': '119',
     'key': 'g',
     'position_factor': -9,
     'keyboard': 'g',
     'clef': 'g',
     'white_key': True,
     },
    {'pid': '130',
     'key': 'g1b',
     'position_factor': 10,
     'keyboard': 'f',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '130',
     'key': 'f1#',
     'position_factor': 9,
     'keyboard': 'f',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '129',
     'key': 'f1',
     'position_factor': 9,
     'keyboard': 'f',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '128',
     'key': 'e1',
     'position_factor': 8,
     'keyboard': 'e',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '127',
     'key': 'e1b',
     'position_factor': 8,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '127',
     'key': 'd1#',
     'position_factor': 7,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '126',
     'key': 'd1',
     'position_factor': 7,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '126',
     'key': 'd1b',
     'position_factor': 7,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '125',
     'key': 'c1#',
     'position_factor': 6,
     'keyboard': 'c',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '124',
     'key': 'c1',
     'position_factor': 6,
     'keyboard': 'c',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '123',
     'key': 'b',
     'position_factor': 5,
     'keyboard': 'b',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '122',
     'key': 'bb',
     'position_factor': 5,
     'keyboard': 'b',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '122',
     'key': 'a#',
     'position_factor': 4,
     'keyboard': 'a',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '121',
     'key': 'a',
     'position_factor': 4,
     'keyboard': 'a',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '120',
     'key': 'ab',
     'position_factor': 3,
     'keyboard': 'a',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '120',
     'key': 'g#',
     'position_factor': 3,
     'keyboard': 'g',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '119',
     'key': 'g',
     'position_factor': 3,
     'keyboard': 'g',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '118',
     'key': 'gb',
     'position_factor': 3,
     'keyboard': 'f',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '118',
     'key': 'f#',
     'position_factor': 2,
     'keyboard': 'f',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '117',
     'key': 'f',
     'position_factor': 2,
     'keyboard': 'f',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '116',
     'key': 'e',
     'position_factor': 1,
     'keyboard': 'e',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '115',
     'key': 'eb',
     'position_factor': 1,
     'keyboard': 'e',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '115',
     'key': 'd#',
     'position_factor': 0,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '114',
     'key': 'd',
     'position_factor': 0,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '113',
     'key': 'db',
     'position_factor': 0,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '113',
     'key': 'c#',
     'position_factor': -1,
     'keyboard': 'c',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '112',
     'key': 'c',
     'position_factor': -1,
     'keyboard': 'c',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '111',
     'key': 'B',
     'position_factor': -2,
     'keyboard': 'b',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '110',
     'key': 'Bb',
     'position_factor': -2,
     'keyboard': 'b',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '110',
     'key': 'A#',
     'position_factor': -3,
     'keyboard': 'a',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '109',
     'key': 'A',
     'position_factor': -3,
     'keyboard': 'a',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '108',
     'key': 'Ab',
     'position_factor': -3,
     'keyboard': 'a',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '108',
     'key': 'G#',
     'position_factor': -4,
     'keyboard': 'g',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '107',
     'key': 'G',
     'position_factor': -4,
     'keyboard': 'g',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '106',
     'key': 'Gb',
     'position_factor': -4,
     'keyboard': 'g',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '106',
     'key': 'F#',
     'position_factor': -5,
     'keyboard': 'f',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '105',
     'key': 'F',
     'position_factor': -5,
     'keyboard': 'f',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '104',
     'key': 'E',
     'position_factor': -6,
     'keyboard': 'e',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '103',
     'key': 'Eb',
     'position_factor': -6,
     'keyboard': 'e',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '103',
     'key': 'D#',
     'position_factor': -7,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '102',
     'key': 'D',
     'position_factor': -7,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': True,
     },
    {'pid': '101',
     'key': 'Db',
     'position_factor': -7,
     'keyboard': 'd',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '101',
     'key': 'C#',
     'position_factor': -8,
     'keyboard': 'c',
     'clef': 'f',
     'white_key': False,
     },
    {'pid': '100',
     'key': 'C',
     'position_factor': -8,
     'keyboard': 'c',
     'clef': 'f',
     'white_key': True,
     },
]

